management:
  #actuator port change
  server:
    port: 8080

  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Actuator
    username: root
    password: 12345678

info:
  app:
    name: SungYunHwan
    company: yh

logging:
  level:
    hello.controller: debug
server:
  tomcat:
    mbeanregistry:
      enabled: true
